application: sungchi9
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- deferred: on
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /static
  static_dir: application/static

- url: .*
  script: main.app

libraries:
- name: markupsafe
  version: latest